### ISSUE TITLE
Error: Invalid summoner name.

### ISSUE THREAD

**Issue by twardle** [stephenpoole/op.gg-api#11]
while debugging I noticed I kept getting the following error:
```
{ Error: Invalid summoner name.
    at ErrorExtended (C:\Users\Tyler\workspace\javascript\node_modules\op.gg-api\lib\Responses\Error.js:4:3)
    at SummaryNormal.Promise (C:\Users\Tyler\workspace\javascript\node_modules\op.gg-api\client.js:151:48)
    at Promise._execute (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\promise.js:79:10)
    at opgg.SummaryNormal (C:\Users\Tyler\workspace\javascript\node_modules\op.gg-api\client.js:149:14)
    at getData (C:\Users\Tyler\workspace\javascript\index.js:44:22)
    at getNeighbors (C:\Users\Tyler\workspace\javascript\index.js:106:4)
    at opgg.SummaryNormal.catch.then.error (C:\Users\Tyler\workspace\javascript\index.js:71:5)
    at tryCatcher (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Tyler\workspace\javascript\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) code: 400 }
```
The names that cause it seem to be pretty arbitrary, some contain spaces which throw the error while others that have a space search without a problem.  Special characters also seem to be arbitrarily causing this.

I've tried escaping all regular expression characters and that doesn't seem to work either.  As you can see, the list of names that throw the invalid summoner name seems a little arbitrary.

A short list of names causing this error:

> PrtyPinkPrincess
> AirMarshal50Cent
> RiotMustachinato
> Cptn+JakeSparrow
> ÉFX
> ReadyForSumSalad
> Tentative+Toucan
> MajTom2GrndCntrl
> Cautious+Ostrich
> tugginonmypuddin

Long list of names checked:

- Zuurah
- enfant+calcium
- Neko++Kush
- Xodiqc
- vBreaker
- Figgu
- Locomon
- LutsWaffle
- Wolf+Samurai
- Dierka
- Tallicus
- RpkZ150
- Kanzza
- Joshuarrichie
- hinamiu
- TimmyPage
- Mr+Cupcake
- His+Paragon
- PrtyPinkPrincess
- Delicious808
- Papashan
- pYrre
- HalfSaiyan
- MikkieP33
- urzu2
- lldeejeell
- Apple+Paiii
- AirMarshal50Cent
- Khal+Hodor
- liverpooty
- RaleighRhodes
- TheNupuis
- Riot+Adabard
- RiotMustachinato
- Xephei
- Ericb1
- Spartians11
- Weimu
- Diashi001
- Zeetzo
- zewm
- Andiscar
- Skeythera
- Scroobe
- L0n3D0gz
- Asuv
- CottonyTuna
- Sanastin
- happykitty9
- Implankton
- Capt+Cad
- BardOpieOP
- Super+Yams
- bahamut0sic
- farslash
- Luckdraw
- PureNoLove
- WickedSyyk
- N0ragami
- Son+0f+Athena
- MDS+IS+KING
- HAOBI
- Paquay
- Tojo+Ookami
- techh
- Baeo
- Arufa+Ookami+
- Master+Lycan
- SycamoreJoe
- Kalamity1001
- Shiverblaze
- xProphet
- Inda+Skies
- Ravec90
- Cptn+JakeSparrow
- rawked
- KUYMY
- Giggling+Peanut
- MachineIH
- Eat+Sleep+Game
- Wavelength79
- Gangblank
- zandreameow
- Nagaharu
- Mid+Lane+Mage
- Im+Urgot
- King+Gankins
- BerserkerRL
- Zoom+Boom+Raka
- 6oogle
- SexualPanda2
- SexualPanda21
- Jin+Astora
- sixpack69
- Harry+McRainbow
- Stêvøy
- Jointedcape6
- SpadesXZ
- Moon+Mooon
- Omar218
- Marixza+Bot
- Apachies
- akame115
- XoCandyoX
- The+NaCl+Lord
- C4+In+My+Turban
- ÉFX
- AndreaaLynn
- JarDian101
- goofballpikachu
- IronWraith
- AmbientPanic
- Bird+Lamb+Rock
- CH1CKENGH0ST
- ThrowsWithBaron
- Cheesus+Christ
- Ashaya
- JimblesNotronbo
- Im+Yorick+Mori
- bossupforacheck
- dungood1852
- Lehmbjerg
- Lucious+Lyon
- SqµirtleSquad
- Big+Wang+Theory
- AnotherCookie
- Mr+jogo
- Virgil+Borgia
- DeAtH066
- MissDeath066
- Dougyfresh009
- Sirblueshue
- ReadyForSumSalad
- Pikajewfro
- Nunaniminks
- JHill36
- TmTrollDaddy
- C9+Vitto
- pugman15
- ShowMeTheLight
- exreaper
- Tweek808
- SuperPhung
- BBQ+Leona+Only
- DerpasaurusRex
- Garign
- whip++sage
- Tentative+Toucan
- MajTom2GrndCntrl
- sub+saharan
- Cautious+Ostrich
- SkumbagJohnny
- Sleazay
- tugginonmypuddin
- MaitreCorbo
- VritraReiRei
- Selolius
- ChronoMakers
- TheWickedKing

**Comment by stephenpoole** [comment]
Arbitrary, you say?

**Comment by twardle** [comment]
Oh, I see. thanks for the quick fix.
